services:
    coquo:
        container_name: coquo
        image: coquo:dev
        ports:
            - 3847:3847
        volumes:
            - ./config:/config
        environment:
            - AUTH_SECRET=dev-secret-do-not-use-in-production
