# WARNING: This is a DEVELOPMENT docker-compose file, it should not be used for production.
version: '3.8'
services:

  coquo:
    image: atocqueville/coquo:latest
    container_name: coquo-next
    ports:
      - 3000:3000
    volumes:
      - ./db-dev:/app/db
    # depends_on:
    #   - db
    # working_dir: /app

  # db:
  #   image: jc21/mariadb-aria
  #   container_name: npm_db
  #   ports:
  #     - 33306:3306
  #   volumes:
  #     - db_data:/var/lib/mysql
