name: Publish Docker image

on:
    push:
        branches:
            - master

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        environment: coquo
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '20'

            - name: Get version from package.json
              id: package_version
              run: echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Log in to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  platforms: linux/amd64,linux/arm64
                  push: true
                  tags: |
                      ${{ secrets.DOCKER_USERNAME }}/coquo:${{ env.VERSION }}
                      ${{ secrets.DOCKER_USERNAME }}/coquo:latest
